### ISSUE TITLE
Is the Python package currently functional?

### ISSUE THREAD

**Issue by wkumler** [CSi-Studio/Aird-SDK#6]
Hi, I'm interested in the Aird file type and am hoping to use the Python package to interface with MS files in comparison to other methods. I'd like to use the Python package for this but I can't figure out how. I've successfully installed v0.0.2 using pip but since the package is a stack of folders it just creates package entries for `Beans`, `Parser`, `Utils`, etc. that don't seem to recognize that the others are installed (e.g. calling `Parser.BaseParser` after `import Parser` doesn't recognize that there are necessary functions in `Compressor` and I get the error `ModuleNotFoundError: No module named "Compressor.IntComp.FastPFor256Wrapper"`. 

I expected to be able to run something like

```python
import AirdSDK
AirdSDK.Parser.BaseParser("path/to/file")
```

Is this the correct method for using Python to interface with Aird files? Is the Python package still under development at all or are you focusing on Java alone now? It would be great to get an example of how to open a file and extract a scan and a chromatogram from it.

**Comment by lumiaoshan** [comment]
Because one of the decoding packages in Aird2.0 is not available in the python environment, the python version of the SDK has not been updated. This question has been bothering me for a long time. Recently, I have been focusing more on the follow-up application based on Java-SDK, using Aird's extremely high decoding speed to develop metabolomics and proteomics data analysis software, so I really did not invest too much time in Python SDK, I'm sorry that I don't have enough time to solve your problem recently.
